version: 2.1
jobs:
  build_windows:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run: npm install
      - run: npm run dist
      - store_artifacts:
          path: /root/project/build

workflows:
  version: 2.1
  build:
    jobs:
      - build_windows