module.exports = {
    perform_flash: 'perform-flash',
    update_faq: 'update-faq',
    update_hex_file: 'update_hex_file',
    devices_list_request: 'devices-list-request',
    kill_avrdude: 'kill_avrdude',
    sensors_list_request: 'sensors-list-request',
    port_list_request: 'port-list-request',
    send_config_request: 'send-config-request',
    download_hex: 'download-hex',
    update_sensor: 'update-sensor',
    reload: 'reload',
    change_language_request: 'change-language-request',
    faq_content: 'faq-content',
    faq_content_error: 'faq-content-error',
    hex_file_content: 'hex_file_content',
    hex_content_error: 'hex_content_error',
    avrdude_done: 'avrdude-done',
    avrdude_response: 'avrdude-response',
    port_list_reply: 'port-list-reply',
    update_flasher_port: 'update-flasher-port',
    hex_download_fail: 'hex-download-fail',
    hex_downloaded: 'hex-downloaded',
    language_popup: 'language-popup',
    wizard_assistant_error: 'wizard-assistant-error',
    dropdown_devices_content: 'dropdown-devices-content',
    dropdown_sensors_content: 'dropdown-sensors-content'

}